services:
  api:
    build: ./api
    ports:
      - 3000:3000
    env_file:
      - ./api/.env
    volumes:
      - assets:/app/public/assets
    develop:
      watch:
        - path: ./app/package.json
          action: rebuild
        - path: ./app/yarn.lock
          action: rebuild
        - path: ./api
          target: /app
          action: sync

  client:
    depends_on:
      - api
    build: ./client
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/yarn.lock
          action: rebuild
        - path: ./client
          target: /app
          action: sync

volumes:
  assets:
